Portfolio/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Portfolio.Models
{
    public class Project
    {
        [Key]
        public int ProjectId { get; set; }
        [StringLength(30)]
        [Required]
        [Display(Name ="Project Name")]
        public string ProjectName { get; set; }

        [Required]
        [Display(Name = "Company")]
        public int CompanyId { get; set; }
        [ForeignKey("CompanyId")]
        public Company Company { get; set; }

        [StringLength(30)]
        public string Role { get; set; }

        [StringLength(1000)]
        [Display(Name = "Project Description")]
        public string ProjectDescription { get; set; }


        [StringLength(10)]
        [Display(Name = "Start Month")]
        public string StartMonth { get; set; }

        [Display(Name = "Start Year")]
        public string StartYear { get; set; }

        [Display(Name = "End Month")]
        [StringLength(10)]
        public string EndMonth { get; set; }
        
        [Display(Name = "End Year")]
        public string EndYear { get; set; }

        public bool Current { get; set; }

        [Display(Name = "Technologies Used")]
        public string TechnologiesUsed { get; set; }



    }
}

Portfolio/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Portfolio.Data;
using Portfolio.Models;

namespace Portfolio.Controllers
{
    public class CompaniesController : Controller
    {
        private PortfolioDBContext db = new PortfolioDBContext();

        // GET: Companies
        public ActionResult Index()
        {
            return View(db.Companies.ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompanyId,CompanyName,CompanyLocation,JobTitle")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompanyId,CompanyName,CompanyLocation,JobTitle")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Portfolio/Controllers/ProjectsController.cs
using Portfolio.Data;
using Portfolio.Models;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace Portfolio.Controllers
{
    public class ProjectsController : Controller
    {
        private PortfolioDBContext db = new PortfolioDBContext();

        // GET: Projects
        //used
        public ActionResult Index()
        {
            var projects = db.Companies.Include(p=>p.Projects);
            return View(projects.ToList());
        }

        // GET: Projects/Details/5
        //used
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Include(c => c.Company).Where(x => x.ProjectId == id).FirstOrDefault();
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProjectId,ProjectName,StartMonth,EndMonth,StartYear,EndYear,Current,ProjectDescription,TechnologiesUsed,Role,CompanyId")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", project.CompanyId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", project.CompanyId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProjectId,ProjectName,StartMonth,EndMonth,StartYear,EndYear,Current,ProjectDescription,TechnologiesUsed,Role,CompanyId")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyId = new SelectList(db.Companies, "CompanyId", "CompanyName", project.CompanyId);
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        public PartialViewResult ShowProjects(int id)
        {
            List<Company> companies= new List<Company>();
            if(id==0)
            {
                companies = db.Companies.Include(p => p.Projects).ToList();
                return PartialView("_ShowProject", companies);
            }
            else
            {
                companies = db.Companies.Where(x => x.CompanyId == id).Include(p => p.Projects).ToList();
            }
            return PartialView("_ShowProject", companies);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Portfolio/Views/Projects/Create.cshtml
@model Portfolio.Models.Project
@using Portfolio.Models.Constants
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                <input type="button" value="Add New Company" onclick="location.href='@Url.Action("Create", "Companies")'" />
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StartMonth, new SelectList(new Months().months, ""), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StartYear, new SelectList(Enumerable.Range(2001, (DateTime.Now.Year - 2001) + 1), DateTime.Now.Year), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" id="EndMonthDiv">
            @Html.LabelFor(model => model.EndMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EndMonth, new SelectList(new Months().months, ""), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" id="EndYearDiv">
            @Html.LabelFor(model => model.EndYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.EndYear, new SelectList(Enumerable.Range(2001, (DateTime.Now.Year - 2001) + 1), DateTime.Now.Year), new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Current, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    <input type="checkbox" id="current_check_project" />
                    @Html.ValidationMessageFor(model => model.Current, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TechnologiesUsed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TechnologiesUsed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TechnologiesUsed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
@section Scripts
{
    <script>
        $("#current_check_project").on("click", function () {
            var current = $('#current_check_project').is(':checked');
            //alert("this is me");
            if (current) {
                $("#EndYearDiv").hide();
                $("#EndMonthDiv").hide();
            }
            else {
                $("#EndYearDiv").show();
                $("#EndMonthDiv").show();
            }
        })
    </script>
}

Portfolio/Views/Projects/Delete.cshtml
@model Portfolio.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Company.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Current)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Current)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProjectDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TechnologiesUsed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TechnologiesUsed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Portfolio/Views/Projects/Details.cshtml
@model Portfolio.Models.Project
@{ 
    var item = Model;
    var current = "Current";
}
<div class="col-md-4 border">
    <div class="card h-100 text-center">
        <img src="~/Images/model_view_controller.jpg" class="card-img-top  w-75" alt="...">
        <div class="card-body text-center">
            <h3 class="card-title"><b>@item.ProjectName</b> - @item.Company.CompanyName</h3>
            <p><b>@item.Role</b></p>
            <p class="card-text">
                @if (item.StartMonth != null)
                {@item.StartMonth}
                @if (item.StartYear != null)
                {@item.StartYear} -
                @if (!@item.Current)
                {@item.EndMonth
                @item.EndYear}
            else
            {@current}
            </p>
            <p class="card-text">@item.ProjectDescription</p>
        </div>
    </div>
</div>

Portfolio/Views/Projects/Edit.cshtml
@model Portfolio.Models.Project

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartMonth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndMonth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndMonth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndMonth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EndYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Current, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Current)
                    @Html.ValidationMessageFor(model => model.Current, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProjectDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProjectDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TechnologiesUsed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TechnologiesUsed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TechnologiesUsed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Role, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Role, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Role, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyId, "CompanyId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Portfolio/Views/Projects/Index.cshtml
@model List<Portfolio.Models.Company>

@{
    ViewBag.Title = "Index";
}
<head>
    <link href="~/Content/Custom/Projects.css" rel="stylesheet" />
</head>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="vertical-menu">
                <a id="0" class="active projectSelection">All</a>
                @foreach (var item in Model)
                {
                    <a id="@item.CompanyId" class="projectSelection">@item.CompanyName</a>
                }
            </div>
        </div>
        <div class="col-9">
            <div id="projectsArea" class="projectsArea">

            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    $(".projectSelection").on("click", function () {
        var Id = $(this).attr("id");
        $(".projectSelection").each(function () {
            $(this).removeClass("active");
        })
        $(this).addClass("active");

        $.ajax({
            type: "POST",
            url: "/projects/ShowProjects",
            data: JSON.stringify({ "id": Id }),
            contentType: "application/json charset=utf-8",
            success: function (data) {
                var d = data;
                $("#projectsArea").html(data);
            },
            error: function () {
                console.error("Error in show projects");
            }
        })
    });
    $(document).ready(function () {
        var Id = 0;
        $.ajax({
            type: "POST",
            url: "/projects/ShowProjects",
            data: JSON.stringify({ "id": Id }),
            contentType: "application/json charset=utf-8",
            success: function (data) {
                $("#projectsArea").html(data);
            },
            error: function () {
                console.error("Error in show projects");
            }
        })
    })
</script>

Portfolio/Views/Projects/_ShowProject.cshtml
@model List<Portfolio.Models.Company>
@{
    var current = "Current";
}
<div class="row ">
    @foreach (var it in Model)
    {
        foreach (var item in it.Projects)
        {
            <div class="ProjectView" id="@item.ProjectId">
                <a href="@Url.Action("Details","Projects",new { id = item.ProjectId })">
                    <div class="col-md-4 border">
                        <div class="card h-100 text-center">
                            <img src="~/Images/model_view_controller.jpg" class="card-img-top  w-75" alt="...">
                            <div class="card-body text-center">
                                <h3 class="card-title"><b>@item.ProjectName</b> - @item.Company.CompanyName</h3>
                                <p><b>@item.Role</b></p>
                                <p class="card-text">
                                    @if (item.StartMonth != null)
                                    {@item.StartMonth}
                                    @if (item.StartYear != null)
                                    {@item.StartYear} -
                                    @if (!@item.Current)
                                    {@item.EndMonth
                                    @item.EndYear}
                                else
                                {@current}
                                </p>
                                <p class="card-text">@item.ProjectDescription</p>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        }

    }
</div>